### ISSUE TITLE
0x51 Check Control Status

### ISSUE THREAD

**Issue by NoobOnTour024** [piersholt/wilhelm-docs#6]
Hi there,

I've bee using this command in a project, so I gathered some info regarding which bit indicates what exactly.
Command is not very complicated, similar to https://github.com/piersholt/wilhelm-docs/blob/master/lcm/5b.md 

Let me know if you want me to contribute.

Cheers!
NoobOntour024

**Comment by piersholt** [comment]
Hey mate,

That would be good. I have limited examples of the command in use as my car has been in pieces since 2020.

https://github.com/piersholt/wilhelm-docs/blob/master/CONTRIBUTING.md

**Comment by NoobOnTour024** [comment]
Created the PR

**Comment by piersholt** [comment]
Super interesting, thanks!

Am I correct in thinking this command pertains only to low clusters?

<img width="247" alt="Screen Shot 2023-03-22 at 10 53 34 am" src="https://user-images.githubusercontent.com/4232443/226767532-5ef38a6e-e0a4-488d-afb0-cf4d1c3caf29.png">

**Comment by NoobOnTour024** [comment]
Just noticed I forgot to link to the new page from readme.md so I created a new merge request.

Yes, most of this is used on the Low clusters indeed to trigger the telltales. Seatbelt and Key left in ignition are also used by the High cluster I assume.

**Comment by piersholt** [comment]
No worries. I added it while I was expanding the docs 😄 

I think you're right RE high cluster. I noted the non-CCM warning lamps when I was reviewing the specific flags. Interestingly, they look region dependent. My manual doesn't have any reference to a seatbelt warning, and there's some variation in the symbols.

I'll test my high cluster and see what turns up.

**Comment by piersholt** [comment]
It _looks_ like the command is specific to the low cluster. I couldn't get the high cluster to respond in any way.

**Comment by piersholt** [comment]
@NoobOnTour024 do you want to sense check this before I commit?

I've basically padded out the use cases via references to the operator manual.

https://github.com/piersholt/wilhelm-docs/blob/feature/0x51/lcm/51.md

**Comment by NoobOnTour024** [comment]
Looks good to me!

**Comment by piersholt** [comment]
Merged!

Thanks for contributing!
