### ISSUE TITLE
contact

### ISSUE THREAD

**Issue by uragan1987** [piersholt/wilhelm-docs#7]
hey piersholt
can i have your contact, need to ask you something about one of your repositories
dont know how to contact you,
maybe you can add me on discord : uragan1987#5114
or you send me a mail

**Comment by piersholt** [comment]
I gather this is in regards to ediabas-sgbd?

See https://github.com/github/dmca/blob/master/2022/11/2022-11-28-bmw-2.md.

**Comment by uragan1987** [comment]
Was it your project?

**Comment by uragan1987** [comment]
I got same info, Maybe you have old files?

**Comment by piersholt** [comment]
> Was it your project?

Yes.

> Maybe you have old files?

Yes, but can't be distributed at this time.
